server:
  port: 8000

spring:
  application:
    name: footballresource
  security:
    oauth2:
      resourceserver:
        jwt:
          # `audiences` is a list of the JWT clients that are allowed to access the resource server.
          audiences:
            - football
            - football-ui
          # `issuer-uri` indicates all the endpoints of the authorization server including the public key location.
          issuer-uri: http://localhost:9000

management:
  endpoints:
    web:
      exposure:
        include: health,env,metrics,beans,loggers
