server:
  port: 8000

spring:
  application:
    name: footballresource
  security:
    oauth2:
      resourceserver:
        jwt:
          # `audiences` is a list of the JWT clients that are allowed to access the resource server.
          audiences:
            - football
            - football-ui
          # `issuer-uri` indicates all the endpoints of the authorization server including the public key location.
          issuer-uri: http://localhost:9000
  datasource:
    url: jdbc:postgresql://localhost:5432/football
    username: football
    password: football

management:
  endpoints:
    web:
      exposure:
        include: health,env,metrics,beans,loggers,football
  endpoint:
    health:
      probes:
        # proves are enabled automatically under Kubernetes environment
        enabled: true

football:
  folder: teams
