server:
#  port: 8000
  port: 0

#logging:
#  level:
#    org.springframework.security: trace

spring:
  application:
    # Identifies the application in distributed tracing.
    name: footballresource
  security:
    oauth2:
      resourceserver:
        jwt:
          # `audiences` is a list of the JWT clients that are allowed to access the resource server.
          audiences:
            - football
            - football-ui
          # `issuer-uri` indicates all the endpoints of the authorization server including the public key location.
          issuer-uri: http://localhost:9000
  datasource:
    url: jdbc:postgresql://localhost:5432/football
    username: user
    password: user
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    # For Testcontainers to work
    # But not needed if you have Flyway or Liquibase
#    generate-ddl: true
    # Should not be used in production
    show-sql: true
  flyway:
    baseline-on-migrate: true
    baseline-version: 0

management:
  endpoint:
    health:
      probes:
        # proves are enabled automatically under Kubernetes environment
        enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics,beans,loggers,football,prometheus
  # Tracing is useful in showing the relationship between the services in a distributed system.
  tracing:
    sampling:
      # By default, only 10% of the requests are sampled. This ensures 100% of the requests are sampled.
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

football:
  folder: teams

eureka:
  client:
    service-url:
      # Eureka server URL
      defaultZone: http://localhost:8761/eureka/
