server:
  port: 8761
spring:
  application:
    name: footballregistry
#  config:
#    import: optional:configserver:http://localhost:8888
eureka:
  client:
    # Followings prohibits the Eureka server from registering itself as a client.
    register-with-eureka: false
    fetch-registry: false
