spring:
  application:
    name: album
  config:
    import: optional:configserver:http://localhost:8888
server:
  # The port number will be overwritten by the Config Server.
  port: 8081
football:
  api:
    url: http://localhost:8080
eureka:
  client:
    service-url:
      # Eureka server URL
      defaultZone: http://localhost:8761/eureka/
