spring:
  application:
    name: album
server:
  port: 8081
football:
  api:
    url: http://localhost:8080
eureka:
  client:
    service-url:
      # Eureka server URL
      defaultZone: http://localhost:8761/eureka/
