# Spring Cloud Config Server exposes the following paths:
# /{application}/{profile}[/{label}]
# /{application}-{profile}.yml
# /{label}/{application}-{profile}.yml
# /{application}-{profile}.properties
# /{label}/{application}-{profile}.properties
server:
  port: 8888
spring:
  application:
    name: footballconfig
  cloud:
    config:
      server:
        git:
          uri: https://github.com/drevispas/eureka-config
